# Generated by Django 6.0.3 on 2026-03-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=150, unique=True, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=100, verbose_name='TÍTULO')),
                ('autor', models.CharField(max_length=100, verbose_name='AUTOR')),
                ('genero', models.CharField(max_length=50, verbose_name='GÊNERO')),
                ('ano_publicacao', models.IntegerField(verbose_name='Ano de Publicação')),
                ('editora', models.CharField(max_length=100, verbose_name='EDITORA')),
                ('paginas', models.IntegerField(verbose_name='Total de Páginas')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('emprestado', 'Emprestado'), ('eliminado', 'Eliminado')], default='disponivel', max_length=25, verbose_name='STATUS')),
                ('localizacao', models.CharField(max_length=100, verbose_name='LOCAL')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Lista de Livros',
                'ordering': ('isbn',),
            },
        ),
    ]
