# Generated by Django 6.0.3 on 2026-04-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='TÍTULO')),
                ('diretor', models.CharField(max_length=100, verbose_name='DIRETOR')),
                ('genero', models.CharField(max_length=50, verbose_name='GÊNERO')),
                ('data_lancamento', models.IntegerField(verbose_name='DATA LANÇAMENTO')),
                ('duracao', models.IntegerField(verbose_name='DURAÇÃO')),
                ('streaming', models.CharField(max_length=100, verbose_name='STREAMING')),
                ('classificacao', models.CharField(max_length=25, verbose_name='CLASSIFICAÇÃO')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Lista de Filmes',
                'ordering': ('data_lancamento', 'titulo'),
            },
        ),
    ]
